SECRET_KEY = 'gxcfzrilhnlkjbzee'

SQLALCHEMY_DATABASE_URI = 'sqlite:///bootcamp.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False

REDIS_URL = 'redis://localhost:6379/0'
APP_TIMEZONE = 'Asia/Kolkata'

CACHE_KEY_PREFIX = 'hospital_management'
CACHE_DEFAULT_TIMEOUT = 300
CACHE_DOCTORS_TIMEOUT = 180
CACHE_DEPARTMENTS_TIMEOUT = 600
CACHE_ADMIN_TIMEOUT = 120

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 1800

MAIL_SENDER = 'no-reply@localhospital.app'
MAIL_OUTBOX_DIR = 'instance/outbox'
EXPORTS_DIR = 'instance/exports'
REPORTS_DIR = 'instance/reports'
